const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { createApp } = require('../dist/create-app');
const key = 'sunscript-analytics-consent-v1';
(async () => {
  delete process.env.UMAMI_WEBSITE_ID; delete process.env.UMAMI_SCRIPT_URL; delete process.env.UMAMI_HOST_URL;
  let app = await createApp(); await app.listen(0, '127.0.0.1');
  let browser;
  try {
    const disabled = await fetch(await app.getUrl());
    assert(!(await disabled.text()).includes('/assets/analytics.js'));
    assert(!disabled.headers.get('content-security-policy').includes('umami'));
    await app.close();
    process.env.UMAMI_WEBSITE_ID = '94db1cb1-74f4-4a40-ad6c-962362670409';
    process.env.UMAMI_SCRIPT_URL = 'https://cloud.umami.is/script.js';
    app = await createApp(); await app.listen(0, '127.0.0.1');
    const base = await app.getUrl();
    const response = await fetch(base);
    const csp = response.headers.get('content-security-policy');
    assert(csp.includes("script-src 'self' https://cloud.umami.is"));
    assert(csp.includes("connect-src 'self' https://api-gateway.umami.dev"));
    browser = await chromium.launch({ channel: 'msedge', headless: true });
    const context = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
    let loads = 0;
    await context.route('https://cloud.umami.is/**', route => {
      loads++;
      return route.fulfill({ contentType: 'application/javascript', body: `
        window.captured = [];
        window.umami = { track: callback => {
          window.captured.push(callback({ url: location.href, referrer: document.referrer }));
          return Promise.resolve();
        }};` });
    });
    const page = await context.newPage();
    await page.goto(base + '/?email=secret@example.com#private');
    await page.locator('.analytics-consent').waitFor();
    assert.equal(loads, 0);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: require('node:path').join(require('node:os').tmpdir(), 'sunscript-analytics-mobile.png') });
    await page.getByRole('button', { name: 'Refuser', exact: true }).click();
    await page.reload();
    assert.equal(await page.locator('.analytics-consent').isVisible(), false);
    assert.equal(loads, 0);
    await page.getByRole('button', { name: 'Préférences de statistiques' }).click();
    await page.getByRole('button', { name: 'Accepter', exact: true }).click();
    await page.waitForFunction(() => window.captured?.length === 1);
    assert.equal((await page.evaluate(() => captured[0])).url, '/');
    assert(!(await page.evaluate(() => JSON.stringify(captured))).includes('secret'));
    assert.equal(await page.locator('script[src="https://cloud.umami.is/script.js"]').getAttribute('data-auto-track'), 'false');
    await page.locator('.site-nav a[href="#services"]').click();
    assert.deepEqual((await page.evaluate(() => captured.at(-1))).data, { cible: '/#services', zone: 'nav' });
    await page.locator('.contact-form button[type=submit]').evaluate(el => el.disabled = false);
    await page.locator('#contact-name').fill('Secret Name');
    await page.locator('#contact-email').fill('secret@example.com');
    await page.locator('#contact-need').fill('A private contact message.');
    await page.route('**/contact', route => route.fulfill({ status: 502, json: { message: 'Échec simulé.' } }));
    await page.locator('.contact-form button[type=submit]').click();
    await page.getByText('Échec simulé.', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => captured.filter(e => e.name === 'contact_envoye').length), 0);
    await page.unroute('**/contact');
    await page.route('**/contact', route => route.fulfill({ status: 200, json: { message: 'Envoyé.' } }));
    await page.locator('.contact-form button[type=submit]').click();
    await page.locator('.contact-success').waitFor();
    assert.equal(await page.evaluate(() => captured.filter(e => e.name === 'contact_envoye').length), 1);
    assert(!/secret|private/i.test(await page.evaluate(() => JSON.stringify(captured))));
    const other = await context.newPage(); await other.goto(base + '/service-web');
    await other.waitForFunction(() => window.captured?.length === 1);
    await page.getByRole('button', { name: 'Préférences de statistiques' }).click();
    await page.getByRole('button', { name: 'Refuser', exact: true }).click();
    const count = await page.evaluate(() => captured.length);
    await page.locator('.site-nav a[href="#services"]').click();
    assert.equal(await page.evaluate(() => captured.length), count);
    await other.evaluate(() => document.dispatchEvent(new Event('sunscript:contact-sent')));
    assert.equal(await other.evaluate(() => captured.length), 1);
    const previousLoads = loads;
    await page.reload(); assert.equal(loads, previousLoads);
    await page.evaluate(key => localStorage.setItem(key, JSON.stringify({ choice: 'granted', expires: 1 })), key);
    await page.reload(); await page.locator('.analytics-consent').waitFor();
    assert.equal(loads, previousLoads);
    await page.addInitScript(() => Object.defineProperty(navigator, 'doNotTrack', { value: '1' }));
    await page.reload(); await page.getByRole('button', { name: 'Accepter', exact: true }).click();
    assert.equal(loads, previousLoads);
    await context.close();
    console.log('PASS: disabled mode, CSP, mobile, refusal, consent, clean pageviews/clicks, contact success/failure, withdrawal across tabs, expiry and DNT.');
  } finally { await browser?.close(); await app.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
